defaults:
  - base.yaml
  - finer_base.yaml

training_type: best

model:
  type: finer

  param_grid:
    omega_0: [10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200]
    first_bias_scale: [0.0]

spectrum:
  eval_before_training: false
  crop_sizes: [64, 128]
  selection_methods: ["cropped_64"]
