defaults:
  - base.yaml

optimizer:
  learning_rate: 0.0001


model:
  type: finer
  omega_0: 30
  first_bias_scale: null
  hidden_omega: 30

  param_grid:
    omega_0: [30,]
    first_bias_scale: [null,]
