defaults:
  - base.yaml
  - relu_base.yaml

training_type: best

model:
  param_grid: # modifications to the baseline model
    sigma: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

spectrum:
  eval_before_training: false
  crop_sizes: [64, 128]
  selection_methods: ["cropped_64"]