defaults:
  - base.yaml
  - siren_base.yaml

training_type: all

model:
  param_grid:
    omega_0: [10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200]
    beta_values: [1.0]
    weight_constant: [6,]

